# Generated by Django 2.2.3 on 2019-07-16 22:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=255)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2019, 7, 16, 22, 39, 29, 748678, tzinfo=utc), null=True)),
                ('thumbnail', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
