# Generated by Django 2.2.3 on 2019-07-16 22:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 16, 22, 39, 37, 647074, tzinfo=utc), null=True),
        ),
    ]
